import type { Metadata } from "next";
import { Space_Grotesk, Noto_Sans } from "next/font/google";

import { ReduxProvider } from "../store/Provider";
import { DockPanel } from "../components/layout/DockPanel";
import { Header } from "../components/layout/Header";


import "./globals.css";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-display",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

const notoSans = Noto_Sans({
  variable: "--font-body",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <head>
        {/* eslint-disable-next-line @next/next/no-page-custom-font */}
        <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap" rel="stylesheet" />
      </head>
      <body
        className={`${spaceGrotesk.variable} ${notoSans.variable} antialiased font-display bg-background-dark text-white min-h-screen flex flex-col overflow-x-hidden  `}
      >
        <ReduxProvider>
          
          <div className="relative z-10 flex flex-col h-full grow">
            <Header />
            <main className="flex-1 w-full mx-auto px-6 md:px-12 lg:px-20 py-8 flex-col gap-10">
              {children}
            </main>
            <DockPanel />
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
